// import './FbConnectionStrategy';
// import './FbRegisterStrategy';
// import './GoogleConnectionStrategy';
// import './GoogleRegisterStrategy';
import './JWTstrategies';
import './LocalStrategies';
// export * from './FbRegisterStrategy';
// export * from './FbConnectionStrategy';
// export * from './GoogleRegisterStrategy';
// export * from './GoogleConnectionStrategy';
